version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem2:
    rootdirectory: E:/docker/registry/data
    baseurl: http://192.168.0.20:8080
http:
  addr: :4000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
